version: '3.9'
services:
    postgres:
        container_name: kaspdb
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456
            POSTGRES_DATABASE: tools
        ports:
            - '5434:5432'
  
    adminer:
        image: adminer
        restart: always
        ports:
            - '8080:8080'